name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main   # run workflow only when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 13.200.250.11
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: ./deploy.sh
            
